/* Isolated rich-text browser checks. Requires PLAYWRIGHT_MODULE and Chromium. */
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const net = require('node:net');
const { spawn } = require('node:child_process');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
let passed = 0;
function check(ok, label) { if (!ok) throw Error(label); passed++; console.log('PASS:', label); }
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
(async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'sitefren-text-'));
  fs.copyFileSync(path.join(__dirname, '../sitefren.php'), path.join(root, 'sitefren.php'));
  const port = await new Promise(resolve => {
    const socket = net.createServer(); socket.listen(0, '127.0.0.1', () => {
      const port = socket.address().port; socket.close(() => resolve(port));
    });
  });
  const env = Object.fromEntries(Object.entries(process.env).filter(([key]) => !key.startsWith('POCKET_')));
  env.POCKET_UPDATE_CHECKS = '0'; env.POCKET_INSTALL_TRACKING = '0';
  const server = spawn('php', ['-S', `127.0.0.1:${port}`, '-t', root], { env, stdio: 'ignore' });
  let browser;
  try {
    const url = `http://127.0.0.1:${port}/sitefren.php`;
    for (let i = 0; i < 100; i++) { try { await fetch(url); break; } catch { await delay(50); } }
    browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
    const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
    const errors = []; page.on('pageerror', error => { errors.push(error.message); console.error('PAGE ERROR:', error.stack); });
    await page.goto(url);
    const setup = fs.readFileSync(path.join(root, 'builder-state.php'), 'utf8').match(/Setup code: ([A-Za-z0-9_-]+)/)[1];
    await page.locator('#setupCode').fill(setup); await page.locator('#password').fill('rich-text-testing-password');
    await page.locator('#authButton').click(); await page.locator('#cancelSettings').click();
    const source = '<!doctype html><html><head><style>.special{color:rgb(12,34,56)}h1{font-size:42px}p{font-size:18px}</style></head><body><h1 id="title" class="special">A useful heading</h1><p id="lead" class="special">First <em>styled</em> words and <a href="about.html">our story</a>.</p><p id="plain">Format these words</p><p id="spans">Keep <span class="special" style="letter-spacing:2px">colored words</span> here.</p><a id="nav" href="about.html">About us</a><button id="action">Contact us</button><picture><source srcset="old-photo.png"><img id="hero" class="special" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a4WQAAAAASUVORK5CYII=" alt="Original photo" style="width:160px;height:100px;border-radius:12px"></picture><script>document.body.dataset.executed="yes";</script></body></html>';
    await page.evaluate(async content => {
      const state = await (await fetch('?action=state')).json();
      const response = await fetch('?action=save_file', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': state.csrf }, body: JSON.stringify({ revision: state.revision, path: 'index.html', content }) });
      if (!response.ok) throw Error(await response.text());
    }, source);
    await page.reload(); await page.locator('#editPageBtn').click();
    const frame = page.frameLocator('#preview');
    await frame.locator('#title').click();
    check(await frame.locator('body').getAttribute('data-executed') === null, 'Website scripts remain paused while editing');
    check(await page.locator('#editPageBtn').innerText() === 'Edit', 'Unified entry point is labeled Edit');
    check(await page.locator('#floatingEditor').evaluate(el => getComputedStyle(el).position) === 'fixed', 'Text formatting floats over the preview');
    check(await page.locator('#textToolbar').isVisible(), 'Clicking text opens the floating formatting controls');
    await page.locator('#textHeading').selectOption('H2');
    await frame.locator('h2#title').waitFor();
    check(await frame.locator('#title').getAttribute('class') === 'special', 'Changing heading keeps its class and ID');
    check(await frame.locator('#title').evaluate(el => getComputedStyle(el).color) === 'rgb(12, 34, 56)', 'Heading keeps site styling');
    const select = async (selector, text) => {
      await page.keyboard.press('Escape');
      await page.locator('#floatingEditor').waitFor({ state: 'hidden' });
      await frame.locator(selector).click();
      await frame.locator(selector).evaluate((el, text) => {
        const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT); let node;
        while ((node = walker.nextNode())) {
          const index = node.textContent.indexOf(text);
          if (index < 0) continue;
          const range = document.createRange(); range.setStart(node, index); range.setEnd(node, index + text.length);
          getSelection().removeAllRanges(); getSelection().addRange(range); return;
        }
        throw Error('Text selection not found: ' + text);
      }, text);
      await page.waitForTimeout(60);
    };
    await select('#plain', 'these');
    await page.getByRole('button', { name: 'Bold', exact: true }).click();
    await frame.locator('#plain b').waitFor();
    check(await frame.locator('#plain b').innerText() === 'these', 'Bold formats only the selected words');
    await page.getByRole('button', { name: 'Italic', exact: true }).click();
    await frame.locator('#plain i').waitFor();
    await page.getByRole('button', { name: 'Underline', exact: true }).click();
    await frame.locator('#plain u').waitFor();
    check(true, 'Italic and underline preserve the text selection across toolbar clicks');
    await page.locator('#textLinkBtn').click(); await page.locator('#textLinkURL').fill('javascript:alert(1)');
    await page.locator('#textLinkForm button[type=submit]').click();
    check(await page.locator('#textLinkDialog').isVisible() && await page.locator('#textLinkError').innerText(), 'Unsafe link protocols are rejected');
    await page.locator('#textLinkURL').fill('about.html'); await page.locator('#textLinkForm button[type=submit]').click();
    await frame.locator('#plain a[href="about.html"]').waitFor();
    check(await frame.locator('#plain a').innerText() === 'these', 'Link dialog restores the selected text');
    await select('#lead a', 'our story');
    await page.locator('#textLinkBtn').click();
    check(await page.locator('#textLinkURL').inputValue() === 'about.html', 'Existing link destination remains editable');
    await page.locator('#textLinkURL').fill('mailto:hello@example.com'); await page.locator('#textLinkForm button[type=submit]').click();
    await frame.locator('#lead a[href="mailto:hello@example.com"]').waitFor();
    await select('#spans .special', 'colored'); await page.getByRole('button', { name: 'Bold', exact: true }).click();
    await frame.locator('#spans b').waitFor();
    await select('#nav', 'About us'); await page.keyboard.insertText('Our company');
    await select('#action', 'Contact us'); await page.keyboard.insertText('Get in touch');
    if (process.env.SCREENSHOT_PATH) await page.screenshot({ path: process.env.SCREENSHOT_PATH, fullPage: true });
    await page.locator('#saveVisualBtn').click(); await page.locator('#visualBar').waitFor({ state: 'hidden' });
    const saved = await page.evaluate(async () => (await (await fetch('?action=state')).json()).files['index.html']);
    check(saved.includes('<a id="nav" href="about.html">Our company</a>') && saved.includes('<button id="action">Get in touch</button>'), 'Navigation and button text can be edited without changing their structure');
    check(saved.includes('<h2 id="title" class="special">'), 'Heading level is saved as real semantic HTML');
    check(saved.includes('href="mailto:hello@example.com"') && saved.includes('href="about.html"'), 'Links survive saving without preview URL rewriting');
    check(saved.includes('letter-spacing:2px') && saved.includes('class="special"'), 'Styled spans survive formatting');
    check(!/data-pocket-|contenteditable|Squire/.test(saved), 'Editor helpers and library code never enter website source');
    check(saved.includes('document.body.dataset.executed'), 'Original website script is preserved in the source');
    await page.locator('#editPageBtn').click(); await select('#plain', 'these');
    await page.locator('[data-text-command="clear"]').click();
    await frame.locator('#plain b').waitFor({ state: 'hidden' });
    check(await frame.locator('#plain b,#plain i,#plain u').count() === 0, 'Clear formatting removes emphasis');
    await page.locator('[data-text-command="unlink"]').click();
    await frame.locator('#plain a').waitFor({ state: 'hidden' });
    check(await frame.locator('#plain a').count() === 0, 'Unlink keeps text and removes its link');
    await page.keyboard.press('Escape');
    await frame.locator('#title').click();
    await frame.locator('#title').evaluate(el => {
      const transfer = new DataTransfer(); transfer.setData('text/plain', '<img src=x onerror=alert(1)> pasted');
      transfer.setData('text/html', '<img src=x onerror=alert(1)><script>alert(1)</script>');
      el.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }));
    });
    check(await frame.locator('#title img').count() === 0, 'Pasted markup is inserted as text');
    await page.locator('#cancelVisualBtn').click(); await page.locator('#acceptConfirm').click();
    const afterCancel = await page.evaluate(async () => (await (await fetch('?action=state')).json()).files['index.html']);
    check(afterCancel === saved, 'Cancel preserves the previous draft exactly');
    await page.locator('#editPageBtn').click();
    await frame.locator('#hero').click();
    await page.locator('#imageToolbar').waitFor({ state: 'visible' });
    check(await page.locator('#editImageAlt').inputValue() === 'Original photo', 'Clicking an image opens its editing controls');
    check(await page.locator('#textToolbar').isHidden(), 'Image selection replaces the text toolbar');
    await page.locator('#editImageAlt').fill('A new accessible description');
    await page.locator('#editImageWidth').fill('60');
    await page.locator('#editImageHeight').fill('120');
    await page.locator('#editImageFit').selectOption('contain');
    await page.locator('#visualImageInput').setInputFiles(path.join(__dirname, '../docs/sitefren-icon.svg'));
    await page.waitForFunction(() => !document.querySelector('#saveVisualBtn').disabled);
    await frame.locator('#hero').evaluate(el => new Promise(resolve => {
      if (el.complete) resolve(); else el.addEventListener('load', resolve, { once: true });
    }));
    check((await frame.locator('#hero').getAttribute('src')).startsWith('data:image/svg+xml'), 'Replacement upload updates the selected image immediately');
    await select('#title', 'useful'); await page.keyboard.insertText('updated');
    await page.locator('#saveVisualBtn').click(); await page.locator('#visualBar').waitFor({ state: 'hidden' });
    const imageSaved = await page.evaluate(async () => (await (await fetch('?action=state')).json()).files['index.html']);
    check(/src="assets\/[^"]+\.svg"/.test(imageSaved), 'Saved replacement uses a local asset path');
    check(imageSaved.includes('updated heading') && imageSaved.includes('border-radius: 12px'), 'One save retains text edits, image edits, and unrelated image styling');
    check(imageSaved.includes('A new accessible description') && imageSaved.includes('width: 60%') && imageSaved.includes('object-fit: contain'), 'Image alt text, size and fit persist in the draft');
    check(!imageSaved.includes('old-photo.png') && !/data-pocket-|contenteditable/.test(imageSaved), 'Replacement removes stale picture sources and excludes preview helpers');
    await page.locator('#editPageBtn').click(); await frame.locator('#hero').click();
    await page.locator('#removeVisualImage').click();
    await page.locator('#cancelVisualBtn').click(); await page.locator('#acceptConfirm').click();
    check(await frame.locator('#hero').count() === 1, 'Cancel restores a removed image');
    await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#editPageBtn').click();
    await frame.locator('#hero').click();
    await page.locator('#imageToolbar').waitFor({ state: 'visible' });
    check(await page.locator('#editImageWidth').inputValue() === '60' && await page.locator('#editImageHeight').inputValue() === '120' && await page.locator('#editImageFit').inputValue() === 'contain', 'Reopened image controls reflect saved dimensions and fit');
    const bounds = await page.locator('#floatingEditor').boundingBox();
    check(bounds.x >= 0 && bounds.x + bounds.width <= 390 && bounds.y >= 0 && bounds.y + bounds.height <= 844, 'Image controls stay inside the mobile viewport');
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Formatting toolbar fits a mobile viewport');
    if (process.env.SCREENSHOT_PATH) await page.screenshot({ path: process.env.SCREENSHOT_PATH + '.mobile.png', fullPage: true });
    await page.keyboard.press('Escape');
    await page.setViewportSize({ width: 844, height: 390 });
    await frame.locator('#hero').click();
    await page.locator('#imageToolbar').waitFor({ state: 'visible' });
    const landscape = await page.locator('#floatingEditor').boundingBox();
    check(landscape.y >= 0 && landscape.y + landscape.height <= 390, 'Image panel scrolls within a short landscape viewport');
    await page.locator('#removeVisualImage').click();
    await page.locator('#saveVisualBtn').click(); await page.locator('#visualBar').waitFor({ state: 'hidden' });
    check(await frame.locator('#hero').count() === 0, 'Saving image removal removes only the selected image');
    await page.evaluate(async () => {
      const state = await (await fetch('?action=state')).json();
      const response = await fetch('?action=save_file', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': state.csrf },
        body: JSON.stringify({ revision: state.revision, path: 'pages/gallery.html', content: '<!doctype html><html><body><img id="only" src="old.png" alt="Only image" width="100" height="100"></body></html>' }) });
      if (!response.ok) throw Error(await response.text());
    });
    await page.reload(); await page.locator('#pageSelect').selectOption('pages/gallery.html');
    await page.locator('#editPageBtn').click(); await frame.locator('#only').click();
    await page.locator('#imageToolbar').waitFor({ state: 'visible' });
    const asset = await page.locator('#imageAsset option').nth(1).getAttribute('value');
    await page.locator('#imageAsset').selectOption(asset);
    await page.locator('#saveVisualBtn').click(); await page.locator('#visualBar').waitFor({ state: 'hidden' });
    const gallery = await page.evaluate(async () => (await (await fetch('?action=state')).json()).files['pages/gallery.html']);
    check(gallery.includes('src="../' + asset + '"'), 'Image-only nested pages can replace images with correct relative paths');
    await page.locator('#publishBtn').click(); await page.locator('#acceptConfirm').click();
    await page.waitForFunction(() => document.querySelector('#saveStatus').textContent === 'Published');
    check(fs.readFileSync(path.join(root, 'pages/gallery.html'), 'utf8') === gallery && fs.existsSync(path.join(root, asset)), 'Publishing writes edited image pages and their uploaded assets');
    check(errors.length === 0, 'No uncaught JavaScript errors: ' + errors.join('; '));
    console.log(`${passed} rich-text checks passed.`);
  } finally { if (browser) await browser.close(); server.kill('SIGTERM'); await delay(100); fs.rmSync(root, { recursive: true, force: true }); }
})().catch(error => { console.error(error); process.exitCode = 1; });
